name: Deploy Full-Stack App to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build Go Backend
        run: |
          cd Backend
          go build -o my-go-app main.go

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Frontend Dependencies & Build
        run: |
          cd Frontend
          npm install
          npm run build

      # --- THIS IS THE UPDATED DEPLOYMENT STEP ---
      - name: Deploy Files to Lightsail
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          # Use 'source' and 'target' for reliable file copying
          source: "Backend/my-go-app,Frontend/dist/"
          target: "~/temp_deploy" # Deploy to a temporary directory first

      - name: Activate New Version on Lightsail
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          script: |
            echo "Stopping services..."
            pm2 stop go-api || true
            
            echo "Deploying new backend executable..."
            mv ~/temp_deploy/my-go-app ~/MRF/Backend/my-go-app
            chmod +x ~/MRF/Backend/my-go-app
            
            echo "Deploying new frontend files..."
            sudo rm -rf /var/www/my-react-app/*
            sudo mv ~/temp_deploy/dist/* /var/www/my-react-app/
            
            echo "Setting web directory permissions..."
            sudo chown -R www-data:www-data /var/www/my-react-app
            sudo chmod -R 755 /var/www/my-react-app
            
            echo "Creating/Updating backend .env file..."
            echo "DB_SOURCE=postgresql://myapp_user:${{ secrets.DB_PASSWORD }}@localhost:5432/myapp_db" > ~/MRF/Backend/.env
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> ~/MRF/Backend/.env
            
            echo "Restarting services..."
            cd ~/MRF/Backend
            pm2 restart go-api --update-env
            sudo systemctl restart nginx
            
            echo "Cleaning up temporary directory..."
            rm -rf ~/temp_deploy
            
            echo ">>> Deployment Successful!"
