name: Deploy Full-Stack App to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Build the Go backend
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build Go Backend
        run: |
          cd Backend
          go build -o my-go-app main.go

      # Step 3: Build the React frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Frontend Dependencies & Build
        run: |
          cd Frontend
          npm install
          npm run build

      # Step 4: Securely COPY the built files and migrations to the server
      - name: Copy Files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          source: "Backend/my-go-app,Backend/migrations,Frontend/dist"
          target: "~/MRF_DEPLOY"
          strip_components: 1

      # Step 5: Run activation script on the server
      - name: Activate New Version
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          script: |
            echo "Running database migrations..."
            if ! command -v migrate &> /dev/null
            then
              echo "migrate could not be found, installing..."
              curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-amd64.tar.gz | tar xvz
              sudo mv migrate /usr/local/bin/migrate
            fi
            
            DB_URL="postgres://myapp_user:${{ secrets.DB_PASSWORD }}@localhost:5432/myapp_db?sslmode=disable"
            
            migrate -path ~/MRF_DEPLOY/migrations -database "$DB_URL" up

            echo "Stopping services..."
            pm2 stop go-api || true
            
            echo "Deploying new backend executable..."
            mv ~/MRF_DEPLOY/my-go-app ~/MRF/Backend/my-go-app
            chmod +x ~/MRF/Backend/my-go-app
            
            echo "Ensuring uploads directory exists..."
            mkdir -p ~/MRF/Backend/uploads

            echo "Deploying new frontend files..."
            sudo rm -rf /var/www/my-react-app/*
            sudo mv ~/MRF_DEPLOY/dist/* /var/www/my-react-app/
            
            echo "Setting web directory permissions..."
            sudo chown -R www-data:www-data /var/www/my-react-app
            sudo chmod -R 755 /var/www/my-react-app
            
            echo "Creating/Updating backend .env file..."
            echo "DB_SOURCE=postgresql://myapp_user:${{ secrets.DB_PASSWORD }}@localhost:5432/myapp_db" > ~/MRF/Backend/.env
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> ~/MRF/Backend/.env
            
            echo "Restarting services..."
            cd ~/MRF/Backend
            pm2 restart go-api --update-env
            sudo systemctl restart nginx
            
            echo "Cleaning up..."
            rm -rf ~/MRF_DEPLOY
            
            echo ">>> Deployment Successful!"